### ISSUE TITLE
Set up Workflow to upload to PyPi

### ISSUE THREAD

**Issue by CCorrado** [johnsonandjohnson/nlprov#5]
We should host the python artifact in a central repository (i.e. PyPi, GitHub artifacts) so users can easily include nlprov in their projects without cloning the repository.

More on this here
https://python-packaging-tutorial.readthedocs.io/en/latest/uploading_pypi.html

**Comment by mbellows** [comment]
Manually added to pypi so far: https://pypi.org/project/nlprov/. Now just need to set up a workflow.
